//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LedsGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM")]
        public string COMPort {
            get {
                return ((string)(this["COMPort"]));
            }
            set {
                this["COMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DigitalLastMode {
            get {
                return ((int)(this["DigitalLastMode"]));
            }
            set {
                this["DigitalLastMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnalogLastMode {
            get {
                return ((int)(this["AnalogLastMode"]));
            }
            set {
                this["AnalogLastMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color AnalogLastCustomColorPrincipal {
            get {
                return ((global::System.Drawing.Color)(this["AnalogLastCustomColorPrincipal"]));
            }
            set {
                this["AnalogLastCustomColorPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color analogLastColor1 {
            get {
                return ((global::System.Drawing.Color)(this["analogLastColor1"]));
            }
            set {
                this["analogLastColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color analogLastColor2 {
            get {
                return ((global::System.Drawing.Color)(this["analogLastColor2"]));
            }
            set {
                this["analogLastColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color analogLastColor3 {
            get {
                return ((global::System.Drawing.Color)(this["analogLastColor3"]));
            }
            set {
                this["analogLastColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color analogLastColor4 {
            get {
                return ((global::System.Drawing.Color)(this["analogLastColor4"]));
            }
            set {
                this["analogLastColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color analogLastColor5 {
            get {
                return ((global::System.Drawing.Color)(this["analogLastColor5"]));
            }
            set {
                this["analogLastColor5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color analogLastColor6 {
            get {
                return ((global::System.Drawing.Color)(this["analogLastColor6"]));
            }
            set {
                this["analogLastColor6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color DigitalLastCustomColorPrincipal {
            get {
                return ((global::System.Drawing.Color)(this["DigitalLastCustomColorPrincipal"]));
            }
            set {
                this["DigitalLastCustomColorPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color digitalLastColor1 {
            get {
                return ((global::System.Drawing.Color)(this["digitalLastColor1"]));
            }
            set {
                this["digitalLastColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color digitalLastColor2 {
            get {
                return ((global::System.Drawing.Color)(this["digitalLastColor2"]));
            }
            set {
                this["digitalLastColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color digitalLastColor3 {
            get {
                return ((global::System.Drawing.Color)(this["digitalLastColor3"]));
            }
            set {
                this["digitalLastColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color digitalLastColor4 {
            get {
                return ((global::System.Drawing.Color)(this["digitalLastColor4"]));
            }
            set {
                this["digitalLastColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color digitalLastColor5 {
            get {
                return ((global::System.Drawing.Color)(this["digitalLastColor5"]));
            }
            set {
                this["digitalLastColor5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color digitalLastColor6 {
            get {
                return ((global::System.Drawing.Color)(this["digitalLastColor6"]));
            }
            set {
                this["digitalLastColor6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal TrebleFactor {
            get {
                return ((decimal)(this["TrebleFactor"]));
            }
            set {
                this["TrebleFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal MediumFactor {
            get {
                return ((decimal)(this["MediumFactor"]));
            }
            set {
                this["MediumFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal BassFactor {
            get {
                return ((decimal)(this["BassFactor"]));
            }
            set {
                this["BassFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrebleUseAverage {
            get {
                return ((bool)(this["TrebleUseAverage"]));
            }
            set {
                this["TrebleUseAverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrebleIsXLogScale {
            get {
                return ((bool)(this["TrebleIsXLogScale"]));
            }
            set {
                this["TrebleIsXLogScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int TrebleMinFreq {
            get {
                return ((int)(this["TrebleMinFreq"]));
            }
            set {
                this["TrebleMinFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int TrebleMaxFreq {
            get {
                return ((int)(this["TrebleMaxFreq"]));
            }
            set {
                this["TrebleMaxFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TrebleScaling {
            get {
                return ((int)(this["TrebleScaling"]));
            }
            set {
                this["TrebleScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediumUseAverage {
            get {
                return ((bool)(this["MediumUseAverage"]));
            }
            set {
                this["MediumUseAverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediumIsXLogScale {
            get {
                return ((bool)(this["MediumIsXLogScale"]));
            }
            set {
                this["MediumIsXLogScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int MediumMinFreq {
            get {
                return ((int)(this["MediumMinFreq"]));
            }
            set {
                this["MediumMinFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int MediumMaxFreq {
            get {
                return ((int)(this["MediumMaxFreq"]));
            }
            set {
                this["MediumMaxFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MediumScaling {
            get {
                return ((int)(this["MediumScaling"]));
            }
            set {
                this["MediumScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BassUseAverage {
            get {
                return ((bool)(this["BassUseAverage"]));
            }
            set {
                this["BassUseAverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BassIsXLogScale {
            get {
                return ((bool)(this["BassIsXLogScale"]));
            }
            set {
                this["BassIsXLogScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BassMinFreq {
            get {
                return ((int)(this["BassMinFreq"]));
            }
            set {
                this["BassMinFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int BassMaxFreq {
            get {
                return ((int)(this["BassMaxFreq"]));
            }
            set {
                this["BassMaxFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BassScaling {
            get {
                return ((int)(this["BassScaling"]));
            }
            set {
                this["BassScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TrebleSqrtFactor {
            get {
                return ((decimal)(this["TrebleSqrtFactor"]));
            }
            set {
                this["TrebleSqrtFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal MedioSqrtFactor {
            get {
                return ((decimal)(this["MedioSqrtFactor"]));
            }
            set {
                this["MedioSqrtFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal BassSqrtFactor {
            get {
                return ((decimal)(this["BassSqrtFactor"]));
            }
            set {
                this["BassSqrtFactor"] = value;
            }
        }
    }
}
